insert into place(id, label, location) VALUES (1, 'Le Café du Marché', 'Rue de Conthey 17, 1950 Sion');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (1,'tuesday', '11:30', '15:00');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (1,'tuesday', '18:30', '00:00');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (1,'wednesday', '11:30', '15:00');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (1,'wednesday', '18:30', '00:00');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (1,'thursday', '11:30', '15:00');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (1,'thursday', '18:30', '00:00');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (1,'friday', '11:30', '15:00');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (1,'friday', '18:30', '00:00');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (1,'saturday', '18:00', '00:00');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (1,'sunday', '11:30', '15:00');
insert into place(id, label, location) VALUES (2, 'Casa Ferlin', 'Stampfenbachstrasse 38, 8006 Zürich');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (2,'monday', '11:30', '14:00');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (2,'monday', '18:30', '22:00');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (2,'tuesday', '11:30', '14:00');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (2,'tuesday', '18:30', '22:00');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (2,'wednesday', '11:30', '14:00');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (2,'wednesday', '18:30', '22:00');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (2,'thursday', '11:30', '14:00');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (2,'thursday', '18:30', '22:00');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (2,'friday', '11:30', '14:00');
insert into opening_hour(place_id, day, time_start, time_end) VALUES (2,'friday', '18:30', '22:00');
